apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
        app: practicadsc
        tier: frontend
  template:
    metadata:
      labels:
        app: practicadsc
        tier: frontend
    spec:
      containers:
      - name: practicadsc
        image: antoniochavesgarcia/practicadsc:s1
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8888
